#!/usr/bin/env python3
"""Unit tests for the fork-restore path -- no docker, no real engine.

WHY THIS FILE EXISTS
--------------------
Record 85 §3 proved the restore recipe by hand (86 files, 0 rejects, rebuilt
ROM byte-identical) and §4 filed the absence of a tool as a finding. The tool
now exists, and its one job is materializing a working copy WITHOUT ever
endangering the one that may already be there. So the failure directions get
tests, not just the happy path: a rejecting patch must report loudly and touch
nothing, --force must not destroy the old fork when the restore fails, and the
no-clobber refusal must actually refuse.

Everything is manufactured: a miniature engine git clone, a patch produced by
the same `diff -ruN` shape export_hack.py emits, a binary asset. Same
discipline as test_verify_hack.py: every check gets a negative test.

    python3 -m unittest discover -s tests -v
"""

import json
import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest

TOOLS = pathlib.Path(__file__).resolve().parents[1] / "tools"
sys.path.insert(0, str(TOOLS))

import export_hack  # noqa: E402

ASSET_BYTES = b"\x00\x01\x02\x03"


def git(cwd, *args):
    subprocess.run(["git", "-c", "user.email=t@t", "-c", "user.name=t", *args],
                   cwd=cwd, check=True, capture_output=True)


def make_engine(root: pathlib.Path) -> pathlib.Path:
    """A miniature pinned engine: a real git clone, tagged like a pin."""
    eng = root / "engine"
    (eng / "src").mkdir(parents=True)
    (eng / "Makefile").write_text("all:\n\ttrue\n")
    (eng / "src" / "main.c").write_text("int main(void) { return 0; }\n")
    (eng / "src" / "keep.c").write_text("int keep;\n")
    git(eng, "init", "-q")
    git(eng, "add", "-A")
    git(eng, "commit", "-qm", "pin")
    git(eng, "tag", "test/0")
    return eng


def make_workspace(root: pathlib.Path, eng: pathlib.Path) -> pathlib.Path:
    """A game repo holding the tracked backup: patch + assets + harness.json.

    The patch is generated by `diff -ruN engine/ hacks/mini/` from a scratch
    layout -- the exact shape export_hack.py writes -- not handcrafted, so the
    tests cannot pass on a patch format the real tool never produces.
    """
    scratch = root / "layout"
    fork = scratch / "hacks" / "mini"
    fork.parent.mkdir(parents=True)
    shutil.copytree(eng, fork, ignore=shutil.ignore_patterns(".git"))
    (fork / "src" / "main.c").write_text("int main(void) { return 1; }\n")
    (fork / "src" / "new.c").write_text("int shiny;\n")
    (scratch / "engine").symlink_to(eng)
    r = subprocess.run(["diff", "-ruN", "-x", ".git", "engine/", "hacks/mini/"],
                       cwd=scratch, capture_output=True, text=True)
    assert r.returncode == 1, "the fork must differ from the engine"

    ws = root / "ws"
    (ws / "patches" / "assets" / "mini" / "gfx").mkdir(parents=True)
    (ws / "patches" / "mini.patch").write_text(r.stdout)
    (ws / "patches" / "assets" / "mini" / "gfx" / "tiles.bin").write_bytes(ASSET_BYTES)
    (ws / "harness.json").write_text(json.dumps(
        {"game": "mini", "engine": {"ref": "test/0", "cache": str(eng)}}))
    return ws


class RestoreBase(unittest.TestCase):
    def setUp(self):
        self.tmp = pathlib.Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        self.eng = make_engine(self.tmp)
        self.ws = make_workspace(self.tmp, self.eng)
        self.patch = self.ws / "patches" / "mini.patch"
        self.assets = self.ws / "patches" / "assets" / "mini"


class MaterializeTests(RestoreBase):
    """export_hack.materialize -- the shared recipe itself."""

    def test_round_trip_lands_patch_and_assets(self):
        dest = self.tmp / "out"
        dest.mkdir()
        ok, problems = export_hack.materialize(self.eng, self.patch,
                                               self.assets, dest)
        self.assertTrue(ok)
        self.assertEqual(problems, [])
        self.assertEqual((dest / "src" / "main.c").read_text(),
                         "int main(void) { return 1; }\n")
        self.assertEqual((dest / "src" / "new.c").read_text(), "int shiny;\n")
        self.assertEqual((dest / "src" / "keep.c").read_text(), "int keep;\n")
        self.assertEqual((dest / "gfx" / "tiles.bin").read_bytes(), ASSET_BYTES)
        # git archive, not a clone: the tree must carry no history
        self.assertFalse((dest / ".git").exists())

    def test_rejecting_patch_fails_loudly(self):
        self.patch.write_text(
            "--- engine/src/main.c\n"
            "+++ hacks/mini/src/main.c\n"
            "@@ -1 +1 @@\n"
            "-int main(void) { return 42; }\n"
            "+int main(void) { return 7; }\n")
        dest = self.tmp / "out"
        dest.mkdir()
        ok, problems = export_hack.materialize(self.eng, self.patch,
                                               self.assets, dest)
        self.assertFalse(ok)
        self.assertTrue(any("patch did not apply" in p for p in problems))
        self.assertTrue(any(".rej" in p for p in problems))

    def test_named_missing_asset_is_diagnosed(self):
        # the replay path hands materialize an explicit list; a file the diff
        # named but the assets dir lacks must be reported BY NAME, not surface
        # later as an inexplicable byte mismatch
        dest = self.tmp / "out"
        dest.mkdir()
        ok, problems = export_hack.materialize(
            self.eng, self.patch, self.assets, dest,
            asset_rels=["gfx/tiles.bin", "gfx/ghost.bin"])
        self.assertTrue(ok)          # the tree itself stands
        self.assertTrue(any("ghost.bin" in p for p in problems))
        self.assertEqual((dest / "gfx" / "tiles.bin").read_bytes(), ASSET_BYTES)

    def test_broken_engine_reports_not_crashes(self):
        ok, problems = export_hack.materialize(
            self.tmp / "nowhere", self.patch, self.assets, self.tmp / "out2")
        self.assertFalse(ok)
        self.assertTrue(problems)


class RestoreCliTests(RestoreBase):
    """tools/restore_hack.py -- manners and the never-lose-the-fork ordering."""

    def restore(self, *extra):
        return subprocess.run(
            [sys.executable, str(TOOLS / "restore_hack.py"), "mini",
             "--root", str(self.ws), *extra],
            cwd=self.ws, capture_output=True, text=True)

    def test_fresh_restore(self):
        r = self.restore()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        dest = self.ws / "hacks" / "mini"
        self.assertEqual((dest / "src" / "main.c").read_text(),
                         "int main(void) { return 1; }\n")
        self.assertEqual((dest / "gfx" / "tiles.bin").read_bytes(), ASSET_BYTES)
        man = json.loads((dest / "HACK_MANIFEST.json").read_text())
        self.assertEqual(man["forked_by"], "tools/restore_hack.py")
        self.assertEqual(man["restored_from"], "patches/mini.patch")
        # no scratch dir left behind in hacks/
        leftovers = [p for p in (self.ws / "hacks").iterdir() if p.name != "mini"]
        self.assertEqual(leftovers, [])

    def test_refuses_to_clobber_without_force(self):
        marker = self.ws / "hacks" / "mini" / "PRECIOUS_EDIT.c"
        marker.parent.mkdir(parents=True)
        marker.write_text("int hours_of_work;\n")
        r = self.restore()
        self.assertEqual(r.returncode, 2)
        self.assertIn("--force", r.stderr)
        self.assertTrue(marker.is_file())

    def test_force_replaces(self):
        marker = self.ws / "hacks" / "mini" / "PRECIOUS_EDIT.c"
        marker.parent.mkdir(parents=True)
        marker.write_text("int hours_of_work;\n")
        r = self.restore("--force")
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertFalse(marker.exists())
        self.assertEqual((self.ws / "hacks" / "mini" / "src" / "main.c").read_text(),
                         "int main(void) { return 1; }\n")

    def test_failed_restore_leaves_the_old_fork_standing(self):
        # the safety ordering: even under --force, a patch that rejects must
        # not have deleted anything first
        marker = self.ws / "hacks" / "mini" / "PRECIOUS_EDIT.c"
        marker.parent.mkdir(parents=True)
        marker.write_text("int hours_of_work;\n")
        self.patch.write_text(
            "--- engine/src/main.c\n"
            "+++ hacks/mini/src/main.c\n"
            "@@ -1 +1 @@\n"
            "-int main(void) { return 42; }\n"
            "+int main(void) { return 7; }\n")
        r = self.restore("--force")
        self.assertEqual(r.returncode, 2)
        self.assertIn("RESTORE FAILED", r.stdout)
        self.assertTrue(marker.is_file())
        leftovers = [p for p in (self.ws / "hacks").iterdir() if p.name != "mini"]
        self.assertEqual(leftovers, [])

    def test_missing_patch_is_a_clear_refusal(self):
        self.patch.unlink()
        r = self.restore()
        self.assertEqual(r.returncode, 2)
        self.assertIn("nothing to restore from", r.stderr)


if __name__ == "__main__":
    unittest.main()
