-- Generic symbol-reading verification driver for the Pokémon Thing mode.
--
-- This is the ONE Lua script every verify/*.json spec runs, unmodified.
-- It is the direct analogue of docker/harness/run_spec.lua on the Butano side,
-- and it obeys the same non-negotiable discipline (docs/research/06-ai-harness-
-- lessons.md):
--
--   *** THIS FILE CONTAINS ZERO ASSERTIONS. ***
--
-- It plays back a mechanically-generated input schedule and SAMPLES memory,
-- printing what it read. It never compares anything to anything, never decides
-- pass or fail, and never knows what the spec expects. Every judgement happens
-- outside the emulator, in tools/verify_hack.py, against values this
-- script did not produce and expectations it cannot see. That separation is
-- deliberate: it denies a future agent building a hack any place to hide a
-- reward-hack inside the harness it is being graded by.
--
-- Everything variable -- addresses, offsets, sizes, sample frames, the input
-- timeline -- arrives from outside via build/_probe_data.lua, generated by
-- verify_hack.py from the .sym of the ROM actually under test. Nothing about
-- any particular game state, struct layout or symbol is baked in here, so this
-- file should never need editing when the engine moves or a new hack is built.
--
-- POINTER CHASING / ASLR (doc 44): a probe with deref=true re-reads its base
-- pointer on EVERY SINGLE SAMPLE and never caches it. pokeemerald-expansion
-- re-rolls gSaveBlock1Ptr / gSaveBlock2Ptr at every battle start and map load,
-- so a cached pointer would read a stale, wrong, and eventually meaningless
-- address. The observed pointer is printed alongside the value so the outside
-- judge can see the re-roll for itself.

local data = dofile("/engine/build/_probe_data.lua")

-- Same bit layout as docker/harness/run_spec.lua. Do not diverge.
local GBA_KEYS = {
    A = 1 << 0, B = 1 << 1, Select = 1 << 2, Start = 1 << 3,
    Right = 1 << 4, Left = 1 << 5, Up = 1 << 6, Down = 1 << 7,
    R = 1 << 8, L = 1 << 9,
}

local function keymask(names)
    local mask = 0
    for _, name in ipairs(names or {}) do
        mask = mask | (GBA_KEYS[name] or 0)
    end
    return mask
end

-- Flatten the timeline into a per-frame keymask, resolved once up front.
local frame_keys = {}
local total = 0
for _, step in ipairs(data.timeline) do
    local mask = keymask(step.keys)
    for _ = 1, step.frames do
        total = total + 1
        frame_keys[total] = mask
    end
end
local TOTAL_FRAMES = data.total_frames or total

-- Address regions a dereferenced pointer may plausibly point into. A pointer
-- outside these is reported as invalid rather than read, so a garbage pointer
-- produces an honest "invalid" observation instead of open-bus noise that could
-- be mistaken for data.
local REGIONS = {
    {0x02000000, 0x02040000},  -- EWRAM
    {0x03000000, 0x03008000},  -- IWRAM
    {0x08000000, 0x0A000000},  -- ROM
}

local function plausible(addr)
    for _, r in ipairs(REGIONS) do
        if addr >= r[1] and addr < r[2] then return true end
    end
    return false
end

local function read_n(addr, size)
    if size == 1 then return emu:read8(addr) & 0xff end
    if size == 2 then return emu:read16(addr) & 0xffff end
    return emu:read32(addr) & 0xffffffff
end

local function read_value(probe, addr)
    if probe.size == 0 then                      -- "bytes": a raw hex run
        local out = {}
        for i = 0, probe.length - 1 do
            out[#out + 1] = string.format("%02x", emu:read8(addr + i) & 0xff)
        end
        return table.concat(out)
    end
    return string.format("%0" .. (probe.size * 2) .. "x", read_n(addr, probe.size))
end

local frame = 0
local finished = false

local function update()
    frame = frame + 1
    -- The emulator keeps running between writing DONE and being SIGINTed by the
    -- shell that polls for it -- how many extra frames that is depends on host
    -- scheduling. Everything below the finish line must therefore be a no-op,
    -- or the run has a nondeterministic tail. See the screenshot note below for
    -- what happens when it is not.
    if finished then return end
    emu:setKeys(frame_keys[frame] or 0)

    for _, probe in ipairs(data.probes) do
        local due = (probe.every > 0 and frame % probe.every == 0)
                    or (probe.at and probe.at[frame])
        if due then
            if probe.deref then
                -- RE-READ THE POINTER EVERY SAMPLE. Never cache it. See header.
                local ptr = emu:read32(probe.addr) & 0xffffffff
                if plausible(ptr) and plausible(ptr + probe.offset) then
                    console:log(string.format(
                        "SYMPROBE frame=%d id=%s ptr=%08x value=%s",
                        frame, probe.id, ptr, read_value(probe, ptr + probe.offset)))
                else
                    console:log(string.format(
                        "SYMPROBE frame=%d id=%s ptr=%08x value=invalid",
                        frame, probe.id, ptr))
                end
            else
                console:log(string.format(
                    "SYMPROBE frame=%d id=%s value=%s",
                    frame, probe.id, read_value(probe, probe.addr)))
            end
        end
    end

    if frame >= TOTAL_FRAMES then
        finished = true
        if data.screenshot then
            -- emu:screenshot(path), NOT emu:screenshotToImage() + img:save().
            -- The latter corrupts the heap when called more than once under
            -- this mgba-headless build. This block used to be reachable on
            -- EVERY frame after the finish line (`>=` with no guard), so it
            -- called the corrupting form repeatedly and mgba aborted with
            -- "malloc(): corrupted top size" a few hundred frames later --
            -- reported at a frame number BEFORE the finish line, because the
            -- redirected stdout log is block-buffered and lags reality. It
            -- looked like a mid-run crash and was not. Two independent fixes
            -- are kept deliberately: the `finished` guard, and the direct form.
            emu:screenshot("/engine/build/verify_screenshot.png")
        end
        console:log(string.format("SYMPROBE complete frames=%d", frame))
        local f = io.open("/engine/build/DONE", "w")
        f:write("done")
        f:close()
    end
end

callbacks:add("frame", update)
