#!/usr/bin/env python3
"""Slice 0 boot proof: does the built pokeemerald-expansion ROM actually RUN?

The bar deliberately is not "a .gba file exists" -- that only proves the linker
ran. This boots the ROM under mgba-headless and asserts, from outside the
emulator, that the engine is alive and progressing:

  1. gMain.vblankCounter1 rises strictly across samples. It is incremented by the
     VBlank interrupt handler, so a rising value proves the ROM is executing its
     main loop -- not black-screened, not spinning in the BIOS.
  2. gMain.callback2 resolves to a real symbol in pokeemerald.sym. A garbage
     pointer would not.
  3. gMain.callback2 CHANGES at least once, proving the boot state machine
     advanced between screens rather than hanging on the first one.

(3) is the assertion that would catch a ROM that boots to a static screen and
dies -- the failure a "the file exists" check sails straight past.

This is also the first real exercise of the .sym-reading mechanism that Slice 1's
verification harness is built on: reading a function pointer out of RAM and
resolving it to a NAME is exactly what the hack-verification harness will do, so
proving it here costs nothing extra and de-risks the next slice.

Usage:  python3 tools/boot_proof.py [--frames N] [--timeout SECONDS]
"""

import argparse
import bisect
import pathlib
import re
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import rom_pair  # noqa: E402

import hx  # noqa: E402
REPO_ROOT = hx.HARNESS_ROOT
ENGINE = hx.ENGINE
HARNESS = hx.HARNESS
IMAGE = hx.IMAGE

# Offsets within `struct Main`, from the pinned include/main.h. Named rather than
# magic so a version bump that reorders the struct is a one-line edit here.
MAIN_CALLBACK2 = 0x004
MAIN_VBLANK_COUNTER1 = 0x020
MAIN_STATE = 0x438


def fail(msg):
    print(f"FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def load_symbols(sym_path):
    """Parse a pokeemerald.sym into a sorted table for range lookup.

    The line grammar itself lives in rom_pair.parse_sym_line() -- one copy, so
    a widening (weak and `.hidden` symbols, 2026-08-03) reaches every tool.
    """
    syms = []
    by_name = {}
    for line in sym_path.read_text(errors="replace").splitlines():
        parsed = rom_pair.parse_sym_line(line)
        if parsed is None:
            continue
        addr, _flag, size, name = parsed
        syms.append((addr, size, name))
        by_name.setdefault(name, (addr, size))
    syms.sort(key=lambda t: t[0])
    return syms, by_name


def resolve(syms, addr):
    """Name the symbol containing `addr`, or None. Clears the THUMB low bit."""
    addr &= ~1
    starts = [s[0] for s in syms]
    i = bisect.bisect_right(starts, addr) - 1
    while i >= 0:
        start, size, name = syms[i]
        if size and start <= addr < start + size:
            return name
        if start == addr:
            return name
        # Zero-size symbols can shadow the real containing one; step back past them.
        if start + max(size, 1) <= addr - 0x2000:
            break
        i -= 1
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames", type=int, default=600, help="frames to run (default 600 = ~10s)")
    ap.add_argument("--sample-every", type=int, default=60)
    ap.add_argument("--timeout", type=int, default=120)
    ap.add_argument(
        "--counterfactual", action="store_true",
        help="deliberately probe a WRONG address; this must FAIL. Proves the "
             "PASS depends on reading real engine state rather than passing "
             "vacuously -- the same flipped-assertion discipline the Butano "
             "side uses (see game/platformer/design/log.md).")
    args = ap.parse_args()

    rom = ENGINE / "pokeemerald.gba"
    sym = ENGINE / "pokeemerald.sym"
    if not rom.exists():
        fail(f"{rom} not found -- build the engine first")
    if not sym.exists():
        fail(f"{sym} not found -- run `make syms`")

    syms, by_name = load_symbols(sym)
    if "gMain" not in by_name:
        fail("gMain not found in pokeemerald.sym")
    gmain, gmain_size = by_name["gMain"]
    print(f"==> gMain @ {gmain:08x} (size {gmain_size:#x}), {len(syms)} symbols loaded")
    if args.counterfactual:
        gmain += 0x800  # past the end of struct Main, into unrelated IWRAM
        print(f"==> COUNTERFACTUAL: probing wrong address {gmain:08x} -- expect FAIL")

    build = ENGINE / "build"
    build.mkdir(exist_ok=True)
    (build / "_boot_probe.lua").write_text(
        "-- generated by tools/boot_proof.py; do not hand-edit\n"
        "return {\n"
        f"  callback2 = {gmain + MAIN_CALLBACK2},\n"
        f"  vblank_counter1 = {gmain + MAIN_VBLANK_COUNTER1},\n"
        f"  state = {gmain + MAIN_STATE},\n"
        f"  sample_every = {args.sample_every},\n"
        f"  total_frames = {args.frames},\n"
        "}\n"
    )
    for stale in ("DONE", "boot_screenshot.png"):
        (build / stale).unlink(missing_ok=True)

    script = f"""
set -e
mgba-headless /engine/pokeemerald.gba -l 15 --script /harness/boot_proof.lua \
    > /engine/build/mgba_stdout.log 2>&1 &
PID=$!
START=$SECONDS
while [ ! -f /engine/build/DONE ] && kill -0 $PID 2>/dev/null; do
    if [ $((SECONDS - START)) -ge {args.timeout} ]; then
        echo 'TIMEOUT' >&2; kill -9 $PID 2>/dev/null || true; exit 1
    fi
    sleep 0.05
done
kill -SIGINT $PID 2>/dev/null || true
wait $PID 2>/dev/null || true
"""
    print(f"==> booting under mgba-headless ({args.frames} frames)")
    run = subprocess.run(
        ["docker", "run", "--rm",
         "-v", f"{ENGINE}:/engine", "-v", f"{HARNESS}:/harness",
         "-w", "/engine", IMAGE, "bash", "-c", script],
        capture_output=True, text=True,
    )
    log_path = build / "mgba_stdout.log"
    log = log_path.read_text(errors="replace") if log_path.exists() else ""
    if not (build / "DONE").exists():
        print(log[-2000:], file=sys.stderr)
        fail(f"ROM did not complete {args.frames} frames (docker exit {run.returncode})")

    probe_re = re.compile(
        r"BOOTPROBE frame=(\d+) vblank=(\d+) callback2=([0-9a-f]{8}) state=(\d+)")
    samples = [(int(f), int(v), int(c, 16), int(s))
               for f, v, c, s in probe_re.findall(log)]
    if not samples:
        print(log[-2000:], file=sys.stderr)
        fail("no BOOTPROBE lines in mgba stdout -- the Lua script did not run")

    print(f"==> {len(samples)} samples\n")
    print(f"    {'frame':>6} {'vblank':>8} {'state':>5}  callback2")
    seen_names = []
    for frame, vbl, cb2, state in samples:
        name = resolve(syms, cb2) or "<unresolved>"
        if not seen_names or seen_names[-1] != name:
            seen_names.append(name)
        print(f"    {frame:>6} {vbl:>8} {state:>5}  {cb2:08x} {name}")

    # --- assertions, all evaluated here, outside the emulator ---
    failures = []

    vbls = [s[1] for s in samples]
    if not all(b > a for a, b in zip(vbls, vbls[1:])):
        failures.append(f"gMain.vblankCounter1 did not rise strictly: {vbls}")

    # callback2 is legitimately NULL before the engine installs its first
    # callback, so an early zero sample is expected engine behaviour, not a
    # failure. Everything non-zero must resolve.
    unresolved = [f"{c:08x}" for _, _, c, _ in samples
                  if c != 0 and resolve(syms, c) is None]
    if unresolved:
        failures.append(f"callback2 did not resolve to a symbol: {unresolved}")

    if any(c == 0 for _, _, c, _ in samples[1:]):
        failures.append("gMain.callback2 was NULL after the first sample -- "
                        "the engine lost its callback")

    real_names = [n for n in seen_names if n != "<unresolved>"]
    if len(real_names) < 2:
        failures.append(
            f"gMain.callback2 never changed (stayed {real_names}) -- "
            "the boot state machine did not advance")

    print()
    print(f"    callback2 progression: {' -> '.join(seen_names)}")
    shot = build / "boot_screenshot.png"
    print(f"    screenshot: {shot if shot.exists() else '<none>'}")
    print()

    if failures:
        for f in failures:
            print(f"FAIL: {f}", file=sys.stderr)
        sys.exit(1)
    print("PASS: ROM boots, executes, and advances through boot states.")


if __name__ == "__main__":
    main()
