#!/usr/bin/env python3
"""Deploy a built game/<name>/<name>.gba ROM (plus boxart, screenshot, metadata,
and a LICENSES.txt) onto an Anbernic RG34XX running KNULLI or muOS firmware.

Implements the deployment contract researched in
docs/research/18-device-deployment.md (§7 is the primary spec) and the single
distribution-time attribution obligation from
docs/research/20-license-attribution-obligations.md.

Two transports:
  * Wi-Fi  (default when --host is given): scp/ssh/curl to the running device.
             The nothing-by-hand path -- per-deploy work is fully automatable.
  * Offline (--sd-path): write the same file placements onto a mounted SD card,
             auto-detecting which firmware's layout the card holds.

Per firmware, the placements are:
  KNULLI  ROM  -> /userdata/roms/gba/<name>.gba
          art  -> /userdata/roms/gba/images/<name>-image.png (+ -thumb.png)
          meta -> merged into /userdata/roms/gba/gamelist.xml (upsert by <path>,
                  never blind-overwrite -- other games' entries survive)
          then -> curl http://<host>:1234/reloadgames   (Wi-Fi only)
  muOS    ROM  -> /mnt/mmc/ROMS/gba/<name>.gba
          art  -> MUOS/info/catalogue/Nintendo Game Boy Advance/{box,preview}/<name>.png
          text -> .../text/<name>.txt   (no rescan step; folder name auto-assigns)

Optional per-game deploy inputs (all optional; sensible fallbacks/defaults used):
  game/<name>/deploy/boxart.png       box art
  game/<name>/deploy/preview.png      screenshot (falls back to build/screenshot.png)
  game/<name>/deploy/description.txt  short description
  game/<name>/deploy/meta.json        {name, desc, genre, developer, publisher,
                                       players, releasedate, rating}

Usage:
    tools/deploy.py <name> --target knulli --host 192.168.1.42
    tools/deploy.py <name> --target muos   --host RG34XX
    tools/deploy.py <name> --sd-path /Volumes/SHARE          # firmware auto-detected
    tools/deploy.py <name> --target knulli --host KNULLI --dry-run

Prefer running after docker/build-and-verify.sh <name> and tools/verify_spec.py <name>
have passed. HONEST FLAG: the Wi-Fi scp/ssh/curl contract is complete against the
official docs + firmware source, but has NOT been executed against real RG34XX
hardware from this environment -- see docs/research/18 §7's final bullet.
"""
import argparse
import json
import os
import posixpath
import shlex
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# The muOS catalogue system name for GBA, verified in the assign global.ini
# (docs/research/18 §4). The catalogue folder and (for KNULLI) nothing depend on
# this exact string.
MUOS_SYSTEM = "Nintendo Game Boy Advance"

# Per-firmware defaults for SSH/SCP (docs/research/18 §7).
TARGET_DEFAULTS = {
    "knulli": {"user": "root", "password": "linux", "host": "KNULLI"},
    "muos": {"user": "root", "password": "root", "host": None},
}

# Non-interactive-friendly ssh/scp options: accept a new host key rather than
# blocking on the yes/no prompt, and don't hang forever on an unreachable host.
SSH_OPTS = ["-o", "StrictHostKeyChecking=accept-new", "-o", "ConnectTimeout=10"]

# devkitARM's gba_crt0.s is MPL 2.0 and is linked into every ROM; MPL §3.2 is
# satisfied by pointing recipients at its source. The rest is courtesy notice.
# See docs/research/20-license-attribution-obligations.md.
LICENSES_TXT = """\
LICENSES.txt -- third-party components linked into this Game Boy Advance ROM
Generated by tools/deploy.py (rombench).

This ROM is built with the devkitARM toolchain and the Butano engine. The
components below are compiled or linked into the distributed binary. Personal
use triggers no obligation; these notices accompany the ROM only when it is
distributed (uploaded, shared, or sold).

devkitARM GBA startup code (gba_crt0.s) -- Mozilla Public License 2.0 (MPL-2.0).
  The source for this file is available at:
    https://github.com/devkitPro/devkitarm-crtls
  Per MPL 2.0 section 3.2, this notice informs recipients how to obtain its
  source. The copyleft is file-level only; it does not touch the game's own code.

Butano engine -- zlib license. Butano bundles further components under permissive
  licenses (MIT / ISC / public-domain), including libtonc, ETL, CTTI, gbt-player,
  Maxmod, posprintf and others. Their license texts are in Butano's licenses/
  folder: https://github.com/GValiente/butano/tree/master/licenses

newlib C library -- a collection of BSD-style licenses; notices are reproduced in
  the devkitPro newlib distribution.

Compiler runtime (libgcc) -- distributed under the GCC Runtime Library Exception,
  which imposes no attribution obligation on this binary.
"""

# KNULLI gamelist fields worth emitting, in EmulationStation's conventional order
# (docs/research/18 §4). <path> is handled separately as the upsert key.
KNULLI_META_FIELDS = [
    "name", "desc", "image", "thumbnail", "genre", "players",
    "developer", "publisher", "releasedate", "rating",
]


def fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def j(base, *parts):
    """Join path parts onto a base that may be either a local Path or a remote
    POSIX string, returning the same kind. Keeps the two transports symmetric."""
    if isinstance(base, Path):
        return base.joinpath(*parts)
    return posixpath.join(base, *parts)


# ---------------------------------------------------------------------------
# Pure gamelist.xml merge -- no I/O, fully unit-testable (see the throwaway test
# in the session scratchpad). This is the piece that must never clobber other
# games' metadata, so it is isolated and deterministic.
# ---------------------------------------------------------------------------
def upsert_gamelist(existing_xml, entry: dict) -> str:
    """Merge one <game> entry into an EmulationStation gamelist.

    existing_xml: the current gamelist.xml text, or None/"" for a fresh list.
    entry:        dict with a 'path' key (the upsert identity, e.g. './hero.gba')
                  plus any of the KNULLI_META_FIELDS.

    An existing <game> whose <path> matches is updated field-by-field; a new one
    is appended. All sibling <game> entries are preserved untouched. Returns the
    serialized gamelist text.
    """
    if existing_xml and existing_xml.strip():
        root = ET.fromstring(existing_xml)
        if root.tag != "gameList":
            raise ValueError(f"unexpected gamelist root <{root.tag}>, expected <gameList>")
    else:
        root = ET.Element("gameList")

    path = entry["path"]
    target = None
    for game in root.findall("game"):
        p = game.find("path")
        if p is not None and (p.text or "").strip() == path:
            target = game
            break

    if target is None:
        target = ET.SubElement(root, "game")
        ET.SubElement(target, "path").text = path

    for key, value in entry.items():
        if key == "path" or value is None or value == "":
            continue
        el = target.find(key)
        if el is None:
            el = ET.SubElement(target, key)
        el.text = str(value)

    ET.indent(root, space="  ")
    return '<?xml version="1.0"?>\n' + ET.tostring(root, encoding="unicode") + "\n"


# ---------------------------------------------------------------------------
# Transport channels. Every network / filesystem side effect is behind one of
# these two small classes so the flows below read as pure placement logic, and
# so the network path is easy to eyeball (and later exercise against hardware).
# ---------------------------------------------------------------------------
class Remote:
    """scp/ssh/curl to a running device over Wi-Fi."""

    def __init__(self, host, user, password, dry_run):
        self.host = host
        self.user = user
        self.password = password
        self.dry_run = dry_run
        self._warned_sshpass = False

    def _pre(self):
        if self.password and shutil.which("sshpass"):
            return ["sshpass", "-p", self.password]
        if self.password and not self._warned_sshpass:
            print(f"  note: 'sshpass' not found -- scp/ssh will prompt for the "
                  f"{self.user}@{self.host} password (default '{self.password}'), "
                  f"or use key auth if configured.")
            self._warned_sshpass = True
        return []

    def _run(self, cmd, capture=False):
        printable = " ".join(cmd)
        if self.dry_run:
            print(f"  DRY-RUN exec: {printable}")
            return None
        print(f"  exec: {printable}")
        result = subprocess.run(
            cmd, capture_output=capture, text=True,
        )
        if result.returncode != 0:
            if capture:
                return None
            fail(f"command failed ({result.returncode}): {printable}")
        return result.stdout if capture else ""

    def ensure_dir(self, remote_dir):
        self._run(self._pre() + ["ssh"] + SSH_OPTS +
                  [f"{self.user}@{self.host}", f"mkdir -p {shlex.quote(remote_dir)}"])

    def put(self, local_path, remote_path):
        # The remote path is interpreted by the device's shell (scp semantics),
        # so it must be shell-quoted -- the muOS catalogue path has spaces.
        self.ensure_dir(posixpath.dirname(remote_path))
        self._run(self._pre() + ["scp"] + SSH_OPTS +
                  [str(local_path), f"{self.user}@{self.host}:{shlex.quote(remote_path)}"])

    def put_text(self, text, remote_path):
        tmp = tempfile.NamedTemporaryFile("w", suffix=".tmp", delete=False)
        try:
            tmp.write(text)
            tmp.close()
            self.put(tmp.name, remote_path)
        finally:
            os.unlink(tmp.name)

    def fetch_text(self, remote_path):
        """Return the remote file's text, or None if it doesn't exist / can't be
        read. In dry-run we can't reach the device, so we report None (the merge
        then previews as a fresh-or-additive entry)."""
        if self.dry_run:
            print(f"  DRY-RUN fetch: {self.user}@{self.host}:{remote_path} "
                  f"(assuming absent; real run merges into the live file)")
            return None
        return self._run(
            self._pre() + ["ssh"] + SSH_OPTS +
            [f"{self.user}@{self.host}", f"cat {shlex.quote(remote_path)} 2>/dev/null"],
            capture=True,
        )

    def http_get(self, url):
        self._run(["curl", "-fsS", url])


class Local:
    """Write placements directly onto a mounted SD card (offline mode)."""

    def __init__(self, sd_root, dry_run):
        self.sd_root = Path(sd_root)
        self.dry_run = dry_run

    def _ensure_parent(self, dest: Path):
        if self.dry_run:
            return
        dest.parent.mkdir(parents=True, exist_ok=True)

    def put(self, local_path, dest: Path):
        if self.dry_run:
            print(f"  DRY-RUN copy: {local_path} -> {dest}")
            return
        self._ensure_parent(dest)
        shutil.copyfile(local_path, dest)
        print(f"  copy: {local_path} -> {dest}")

    def put_text(self, text, dest: Path):
        if self.dry_run:
            print(f"  DRY-RUN write: {dest} ({len(text)} bytes)")
            return
        self._ensure_parent(dest)
        dest.write_text(text)
        print(f"  write: {dest} ({len(text)} bytes)")

    def fetch_text(self, dest: Path):
        if isinstance(dest, Path) and dest.is_file():
            return dest.read_text()
        return None

    def http_get(self, url):  # no rescan endpoint when writing a card offline
        print(f"  skip: {url} (offline mode -- gamelist is read at device boot)")


# ---------------------------------------------------------------------------
# Inputs: ROM, optional art/description, metadata.
# ---------------------------------------------------------------------------
def first_existing(*candidates):
    for c in candidates:
        if c and Path(c).is_file():
            return Path(c)
    return None


def load_assets(game_dir: Path, name: str, rom_override: Path = None) -> dict:
    if rom_override is not None:
        rom = rom_override
        if not rom.is_file():
            fail(f"--rom not found: {rom}")
    else:
        rom = game_dir / f"{name}.gba"
        if not rom.is_file():
            fail(f"ROM not found: {rom.relative_to(REPO_ROOT)}\n"
                 f"       build it first:  docker/build-and-verify.sh {name}")
    deploy_dir = game_dir / "deploy"
    assets = {"rom": rom}
    box = first_existing(deploy_dir / "boxart.png", deploy_dir / "box.png")
    if box:
        assets["boxart"] = box
    preview = first_existing(
        deploy_dir / "preview.png", deploy_dir / "screenshot.png",
        game_dir / "build" / "screenshot.png",
    )
    if preview:
        assets["preview"] = preview
    return assets


def load_meta(game_dir: Path, name: str) -> dict:
    meta = {"name": name.replace("-", " ").title(), "desc": ""}
    meta_file = game_dir / "deploy" / "meta.json"
    if meta_file.is_file():
        try:
            meta.update(json.loads(meta_file.read_text()))
        except json.JSONDecodeError as exc:
            fail(f"could not parse {meta_file.relative_to(REPO_ROOT)}: {exc}")
    desc_file = game_dir / "deploy" / "description.txt"
    if desc_file.is_file():
        meta["desc"] = desc_file.read_text().strip()
    return meta


# ---------------------------------------------------------------------------
# Path resolution: concrete destinations for one (target, channel) combination.
# Remote destinations are absolute device POSIX strings; local destinations are
# Paths under the mounted card root.
# ---------------------------------------------------------------------------
def resolve_paths(target: str, channel, name: str, sd2: bool) -> dict:
    local = isinstance(channel, Local)
    p = {}
    if target == "knulli":
        base = (channel.sd_root / "roms" / "gba") if local else "/userdata/roms/gba"
        p["rom_dir"] = base
        p["rom"] = j(base, f"{name}.gba")
        p["boxart"] = j(base, "images", f"{name}-image.png")
        p["thumb"] = j(base, "images", f"{name}-thumb.png")
        p["gamelist"] = j(base, "gamelist.xml")
        p["licenses"] = j(base, f"{name}.LICENSES.txt")
        p["reload_url"] = None if local else f"http://{channel.host}:1234/reloadgames"
    else:  # muos
        mount = "sdcard" if sd2 else "mmc"
        rom_base = (channel.sd_root / "ROMS" / "gba") if local else f"/mnt/{mount}/ROMS/gba"
        cat_base = ((channel.sd_root / "MUOS" / "info" / "catalogue" / MUOS_SYSTEM)
                    if local else f"/mnt/{mount}/MUOS/info/catalogue/{MUOS_SYSTEM}")
        p["rom_dir"] = rom_base
        p["rom"] = j(rom_base, f"{name}.gba")
        p["box"] = j(cat_base, "box", f"{name}.png")
        p["preview"] = j(cat_base, "preview", f"{name}.png")
        p["text"] = j(cat_base, "text", f"{name}.txt")
        p["licenses"] = j(rom_base, f"{name}.LICENSES.txt")
    return p


# ---------------------------------------------------------------------------
# Placement flows.
# ---------------------------------------------------------------------------
def deploy_knulli(channel, paths, assets, meta, name, licenses_file):
    print("-- ROM + LICENSES")
    channel.put(assets["rom"], paths["rom"])
    channel.put(licenses_file, paths["licenses"])

    has_box = "boxart" in assets
    has_thumb = "preview" in assets
    if has_box:
        print("-- box art")
        channel.put(assets["boxart"], paths["boxart"])
    if has_thumb:
        print("-- screenshot / thumbnail")
        channel.put(assets["preview"], paths["thumb"])

    print("-- gamelist.xml (upsert by <path>)")
    entry = {"path": f"./{name}.gba"}
    for field in KNULLI_META_FIELDS:
        if field in ("image", "thumbnail"):
            continue
        if meta.get(field):
            entry[field] = meta[field]
    if has_box:
        entry["image"] = f"./images/{name}-image.png"
    if has_thumb:
        entry["thumbnail"] = f"./images/{name}-thumb.png"

    existing = channel.fetch_text(paths["gamelist"])
    merged = upsert_gamelist(existing, entry)
    channel.put_text(merged, paths["gamelist"])

    if paths.get("reload_url"):
        print("-- refresh EmulationStation game list")
        channel.http_get(paths["reload_url"])


def deploy_muos(channel, paths, assets, meta, name, licenses_file):
    print("-- ROM + LICENSES")
    channel.put(assets["rom"], paths["rom"])
    channel.put(licenses_file, paths["licenses"])

    if "boxart" in assets:
        print("-- box art")
        channel.put(assets["boxart"], paths["box"])
    if "preview" in assets:
        print("-- screenshot / preview")
        channel.put(assets["preview"], paths["preview"])
    if meta.get("desc"):
        print("-- description text")
        channel.put_text(meta["desc"] + "\n", paths["text"])
    print("  (no rescan step -- muOS reads the ROMS/ tree live and auto-assigns 'gba')")


# ---------------------------------------------------------------------------
# Offline firmware auto-detection. Reads real directory-entry casing from
# os.listdir so it works even on a case-insensitive macOS volume, where a plain
# `(root / "roms").is_dir()` would spuriously match a muOS card's ROMS/.
# ---------------------------------------------------------------------------
def detect_firmware(sd_root: Path):
    try:
        entries = set(os.listdir(sd_root))
    except OSError as exc:
        fail(f"cannot read --sd-path {sd_root}: {exc}")
    if "ROMS" in entries and "MUOS" in entries:
        return "muos"
    if "roms" in entries and "system" in entries:
        return "knulli"
    if "ROMS" in entries:
        return "muos"
    if "roms" in entries:
        return "knulli"
    return None


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("name", help="game/<name>/ project whose <name>.gba to deploy; "
                                     "with --rom, just the deployed filename + metadata key")
    parser.add_argument("--rom", help="deploy THIS .gba instead of game/<name>/<name>.gba. "
                                      "The file is still installed as <name>.gba, because that "
                                      "is what the device's gamelist and boxart index on. Lets a "
                                      "ROM built outside this toolkit (e.g. a hacks/ fork) "
                                      "be deployed without a game/ project.")
    parser.add_argument("--target", choices=["knulli", "muos"],
                        help="device firmware (required for Wi-Fi; auto-detected for --sd-path)")
    parser.add_argument("--host", help="device IP or hostname -> Wi-Fi mode (scp/ssh/curl)")
    parser.add_argument("--sd-path", help="mounted SD card root -> offline mode (direct file writes)")
    parser.add_argument("--user", help="SSH user (default: root)")
    parser.add_argument("--password", help="SSH password (default per target: knulli=linux, muos=root)")
    parser.add_argument("--sd2", action="store_true",
                        help="muOS: target the second SD card (/mnt/sdcard) instead of /mnt/mmc")
    parser.add_argument("--dry-run", action="store_true",
                        help="print every action (scp/curl/write) without executing")
    args = parser.parse_args()

    if args.host and args.sd_path:
        fail("choose one transport: --host (Wi-Fi) or --sd-path (offline), not both")
    if not args.host and not args.sd_path:
        fail("specify a transport: --host <ip> for Wi-Fi, or --sd-path <card> for offline")

    # --rom decouples "which ROM" from "which game/<name>/ project", so a ROM
    # built by something other than this toolkit can be deployed. It exists
    # because the  mode's forks live at
    # hacks/<hack>/pokeemerald.gba -- neither in game/ nor named after
    # the project -- and without it the first real-hardware session in this
    # repo would have been a manual file copy, which the nothing-by-hand
    # principle exists to prevent.
    #
    # `name` still decides the DEPLOYED filename and every metadata key, because
    # that is what KNULLI's gamelist.xml and muOS's catalogue index on. So the
    # deployed artifact is <name>.gba whatever the source file is called.
    rom_override = Path(args.rom).expanduser().resolve() if args.rom else None

    game_dir = REPO_ROOT / "game" / args.name
    if not game_dir.is_dir():
        if rom_override is None:
            fail(f"no such project: game/{args.name} "
                 f"(scaffold it with tools/new_game.py)")
        # With --rom there need not be a project at all; optional per-game
        # deploy assets are simply absent and the defaults are used.
        print(f"note: no game/{args.name}/ project -- deploying --rom with "
              f"default metadata. Put boxart/description in "
              f"game/{args.name}/deploy/ to override.")

    assets = load_assets(game_dir, args.name, rom_override)
    meta = load_meta(game_dir, args.name)

    # Resolve transport + target.
    if args.sd_path:
        sd_root = Path(args.sd_path)
        if not sd_root.is_dir():
            fail(f"--sd-path {sd_root} is not a directory (is the card mounted?)")
        detected = detect_firmware(sd_root)
        if args.target and detected and args.target != detected:
            print(f"warning: --target {args.target} but the card at {sd_root} looks like "
                  f"{detected} (roms/system vs ROMS/MUOS). Using --target {args.target}.")
        target = args.target or detected
        if not target:
            fail(f"could not detect firmware at {sd_root} (found neither KNULLI's "
                 f"roms/+system/ nor muOS's ROMS/+MUOS/). Pass --target explicitly.")
        channel = Local(sd_root, args.dry_run)
        transport = f"offline SD card at {sd_root}"
    else:
        if not args.target:
            fail("--target knulli|muos is required for Wi-Fi (--host) deploys")
        target = args.target
        defaults = TARGET_DEFAULTS[target]
        user = args.user or defaults["user"]
        password = args.password or defaults["password"]
        channel = Remote(args.host, user, password, args.dry_run)
        transport = f"Wi-Fi to {user}@{args.host}"

    paths = resolve_paths(target, channel, args.name, args.sd2)

    # Materialize LICENSES.txt into a temp file for the payload.
    lic_tmp = tempfile.NamedTemporaryFile("w", suffix=".LICENSES.txt", delete=False)
    lic_tmp.write(LICENSES_TXT)
    lic_tmp.close()
    licenses_file = lic_tmp.name

    print(f"deploying '{args.name}' -> {target} via {transport}"
          + ("  [DRY-RUN]" if args.dry_run else ""))
    print(f"  ROM:      {assets['rom'].relative_to(REPO_ROOT)}")
    print(f"  box art:  {assets['boxart'].relative_to(REPO_ROOT) if 'boxart' in assets else '(none -- optional)'}")
    print(f"  preview:  {assets['preview'].relative_to(REPO_ROOT) if 'preview' in assets else '(none -- optional)'}")
    print(f"  title:    {meta['name']}")
    print()

    try:
        if target == "knulli":
            deploy_knulli(channel, paths, assets, meta, args.name, licenses_file)
        else:
            deploy_muos(channel, paths, assets, meta, args.name, licenses_file)
    finally:
        os.unlink(licenses_file)

    print()
    if args.dry_run:
        print("dry run complete -- no changes made. Re-run without --dry-run to deploy.")
        return

    print(f"deployed '{args.name}' to {target}.")
    if target == "knulli" and isinstance(channel, Remote):
        print("  The game should appear in EmulationStation with its art. If not, on the")
        print("  device run Game Settings -> Update Gamelists.")
    elif target == "muos":
        print("  Open Explore Content on the device -- the ROMS/gba entry is auto-assigned.")
    print()
    print("one-time manual setup (per docs/research/18 §7, not automatable):")
    print("  flash firmware + first boot, join Wi-Fi, enable SSH/SFTP, power the device on.")
    print("NOTE: this Wi-Fi/offline contract matches the official docs + firmware source")
    print("      but has not been executed against real RG34XX hardware -- treat the first")
    print("      real-device run as verification.")


if __name__ == "__main__":
    main()
