#!/usr/bin/env python3
"""Generate the FREESAVE fixture — doc 67 slate item G, doc 73's record.

WHY THIS EXISTS
---------------
`hacks/` is gitignored, so a fork is not a durable artifact; the thing
that generates it is. Doc 68 put it plainly: a generator that replays
byte-identically is what earns the word "disposable". Without this file, doc 73
would describe an experiment nobody could re-run.

WHAT THE FIXTURE IS FOR
-----------------------
One question: what happens to a save file written before a build's save LAYOUT
changed? The fixture answers it with three builds of one tree, differing only in
`include/config/save.h` and `include/global.h`:

  off      the twelve FREE_* switches FALSE. Writes the .sav.
  on       the twelve FREE_* switches TRUE. sizeof(SaveBlock1) 15568 -> 13152,
           sizeof(SaveBlock2) 3884 -> 2544, so two of the fourteen sectors change
           SIZE and the engine rejects the file outright.
  swapped  four bytes moved from filler1 to the end of SaveBlock1. Every sizeof
           is IDENTICAL, so every checksum still passes and the engine accepts a
           file it can no longer read correctly. This is the case the FREE_*
           switches cannot produce and the one doc 41 actually warns about.

The shared part (src/freesave_probe.c + its header + a one-line hook in
src/main.c) is the same in all three: a debug combo that seeds six values chosen
for WHERE THEY LIVE in SaveBlock1 and then calls the engine's own
TrySavingData(SAVE_NORMAL).

USAGE
-----
    python3 tools/new_hack.py freesave
    python3 tools/make_freesave.py hacks/freesave --arm off
    # build, capture saves/freesave_overworld.ss1, run freesave-write
    python3 tools/make_freesave.py hacks/freesave --arm on
    # build, run freesave-read-flipped  ... and so on

Each arm is applied to a tree that is otherwise at the pin, so the arms are
mutually exclusive: run `--arm off` again to get back to the baseline.

ONE THING THAT WILL BITE WHOEVER RUNS THIS
------------------------------------------
mGBA names its save file after the ROM's FILENAME. All three builds must
therefore be presented to verify_hack.py under the SAME basename
(`roms/<arm>/pokeemerald.gba`), or the second build silently gets a brand-new
empty .sav -- which reads exactly like the save being rejected, in a round whose
entire subject is saves being rejected. That cost a run here.
"""

import argparse
import pathlib
import re
import sys

PROBE_C = '''\
// FREESAVE FIXTURE -- generated by tools/make_freesave.py. Do not hand-edit.
//
// The hook seeds six values chosen for WHERE THEY LIVE, not for what they mean:
//
//   class          field                       SaveBlock1 offset   sector id
//   -------------  --------------------------  -----------------   ---------
//   below the cut  playerPartyCount / party    0x234 / 0x238       1
//   below the cut  money                       0x490               1
//   above the cut  flags[]                     0x1270              1
//   above the cut  vars[]                      0x139C              1
//   the tail       dexSeen / dexCaught         0x3598 / 0x3619     4
//   other block    SaveBlock2.playTimeHours    --                  0
//
// "The cut" is 0x988, the offset of the first `#if FREE_...` member of
// SaveBlock1. Below it, offsets are identical in every arm; at or above it they
// move.
//
// SAVING IS THE ENGINE'S OWN PATH. TrySavingData(SAVE_NORMAL) is what
// src/start_menu.c:1147 calls when a player picks SAVE and confirms. Driving the
// real menu instead would have cost a Start-menu row count that is not
// transferable between save stages, and that is a thing to probe, never guess.

#include "global.h"
#include "main.h"
#include "pokemon.h"
#include "money.h"
#include "event_data.h"
#include "pokedex.h"
#include "save.h"
#include "random.h"
#include "constants/species.h"
#include "constants/flags.h"
#include "constants/vars.h"
#include "freesave_probe.h"

// PUBLISHED BY THE COMPILER, NOT BY HAND. global.h annotates SaveBlock1's tail
// only as `0x3???`, so dexSeen and dexCaught have no written offset to copy --
// and the offsets it DOES annotate are in here too, so a spec can check this
// table against the header before trusting the unannotated rows. `const`, so it
// lives in ROM and costs no RAM.
const u32 gFreeSaveOffsets[FREESAVE_OFFSET_COUNT] =
{
    [FREESAVE_OFF_PARTY_COUNT]  = offsetof(struct SaveBlock1, playerPartyCount),
    [FREESAVE_OFF_PARTY]        = offsetof(struct SaveBlock1, playerParty),
    [FREESAVE_OFF_MONEY]        = offsetof(struct SaveBlock1, money),
    [FREESAVE_OFF_FLAGS]        = offsetof(struct SaveBlock1, flags),
    [FREESAVE_OFF_VARS]         = offsetof(struct SaveBlock1, vars),
    [FREESAVE_OFF_DEX_SEEN]     = offsetof(struct SaveBlock1, dexSeen),
    [FREESAVE_OFF_DEX_CAUGHT]   = offsetof(struct SaveBlock1, dexCaught),
    [FREESAVE_OFF_SB1_SIZE]     = sizeof(struct SaveBlock1),
    [FREESAVE_OFF_SB2_SIZE]     = sizeof(struct SaveBlock2),
    [FREESAVE_OFF_PLAYTIME_HRS] = offsetof(struct SaveBlock2, playTimeHours),
};

// The one piece of state this fixture owns: a LATCH, never cleared, because doc
// 66 paid for that lesson -- a diagnosis value a later frame can overwrite is one
// no sampling rate can be relied on to catch.
EWRAM_DATA u8 gFreeSaveHookLatch = 0;

void FreeSaveSeedAndSave(void)
{
    u16 i;

    // BELOW THE CUT.
    ZeroPlayerPartyMons();
    CreateMon(&gPlayerParty[0], SPECIES_ZIGZAGOON, FREESAVE_MON_LEVEL,
              USE_RANDOM_IVS, FALSE, 0, OT_ID_PLAYER_ID, 0);
    gPlayerPartyCount = 1;
    SetMoney(&gSaveBlock1Ptr->money, FREESAVE_MONEY);

    // ABOVE THE CUT. A PERSISTENT var, not a VAR_TEMP_*: the temp block is
    // cleared on every map load, so a value stored there would read back zero
    // after a reload for a reason that has nothing to do with the save layout --
    // a false positive shaped exactly like the finding.
    FlagSet(FLAG_SYS_POKEDEX_GET);
    VarSet(VAR_RECYCLE_GOODS, FREESAVE_VAR_VALUE);

    // THE TAIL.
    for (i = 1; i <= FREESAVE_DEX_COUNT; i++)
    {
        GetSetPokedexFlag(i, FLAG_SET_SEEN);
        GetSetPokedexFlag(i, FLAG_SET_CAUGHT);
    }

    // SaveBlock2 -- its own sector, its own fate.
    gSaveBlock2Ptr->playTimeHours = FREESAVE_PLAYTIME_HOURS;

    gFreeSaveHookLatch |= FREESAVE_LATCH_SEEDED;

    if (TrySavingData(SAVE_NORMAL) == SAVE_STATUS_OK)
        gFreeSaveHookLatch |= FREESAVE_LATCH_SAVED_OK;
    else
        gFreeSaveHookLatch |= FREESAVE_LATCH_SAVED_FAIL;
}

// CONSUMES the combo -- doc 59 §9.1: a debug hook that reads input without
// consuming it lets the press through to whatever listens next, and the result
// is a correct number about a situation that never happened.
void FreeSaveCheckHook(void)
{
    if ((gMain.newKeys & A_BUTTON)
     && (gMain.heldKeys & L_BUTTON)
     && (gMain.heldKeys & R_BUTTON))
    {
        gMain.newKeys = 0;
        gMain.heldKeys = 0;
        gMain.newAndRepeatedKeys = 0;
        FreeSaveSeedAndSave();
    }
}
'''

PROBE_H = '''\
// FREESAVE FIXTURE -- generated by tools/make_freesave.py. Do not hand-edit.
#ifndef GUARD_FREESAVE_PROBE_H
#define GUARD_FREESAVE_PROBE_H

// Every seeded value is distinctive on purpose: a value a fresh boot could also
// produce cannot tell "the save loaded" from "the save did not".
#define FREESAVE_MON_LEVEL      17
#define FREESAVE_MONEY          123456
#define FREESAVE_VAR_VALUE      0x5AA5
#define FREESAVE_DEX_COUNT      20
#define FREESAVE_PLAYTIME_HOURS 7

#define FREESAVE_LATCH_SEEDED     (1 << 0)
#define FREESAVE_LATCH_SAVED_OK   (1 << 1)
#define FREESAVE_LATCH_SAVED_FAIL (1 << 2)

enum
{
    FREESAVE_OFF_PARTY_COUNT,
    FREESAVE_OFF_PARTY,
    FREESAVE_OFF_MONEY,
    FREESAVE_OFF_FLAGS,
    FREESAVE_OFF_VARS,
    FREESAVE_OFF_DEX_SEEN,
    FREESAVE_OFF_DEX_CAUGHT,
    FREESAVE_OFF_SB1_SIZE,
    FREESAVE_OFF_SB2_SIZE,
    FREESAVE_OFF_PLAYTIME_HRS,
    FREESAVE_OFFSET_COUNT
};

extern const u32 gFreeSaveOffsets[FREESAVE_OFFSET_COUNT];
extern u8 gFreeSaveHookLatch;

void FreeSaveSeedAndSave(void);
void FreeSaveCheckHook(void);

#endif // GUARD_FREESAVE_PROBE_H
'''

MAIN_INCLUDE_ANCHOR = '#include "test_runner.h"\n'
MAIN_INCLUDE_ADD = '#include "test_runner.h"\n#include "freesave_probe.h" // FREESAVE FIXTURE\n'

MAIN_HOOK_ANCHOR = """            rfu_REQ_stopMode();
            rfu_waitREQComplete();
            DoSoftReset();
        }
"""
MAIN_HOOK_ADD = MAIN_HOOK_ANCHOR + """
        // FREESAVE FIXTURE. Placed HERE rather than inside ReadKeys() because
        // this is a frame boundary outside every callback, and it is where the
        // engine already performs its one heavy global input action -- the soft
        // reset three lines up.
        FreeSaveCheckHook();
"""

FILLER_OLD = "    /*0x988*/ u8 filler1[0x34]; // Previously Dex Flags, feel free to remove."
FILLER_NEW = """    /*0x988*/ u8 filler1[0x30]; // FREESAVE SWAP ARM: 0x34 -> 0x30, four bytes
                               // taken here and given back at the end of the
                               // struct, so sizeof(struct SaveBlock1) is
                               // UNCHANGED and every sector keeps its size."""

TAIL_OLD = "    /*0x3???*/ struct WaldaPhrase waldaPhrase;\n    // sizeof: 0x3???\n};"
TAIL_NEW = """    /*0x3???*/ struct WaldaPhrase waldaPhrase;
    // FREESAVE SWAP ARM: the four bytes taken from filler1, returned here. Net
    // size change zero; net effect is that every member between the two edits
    // slides DOWN by 4 while the save system sees an identical layout.
    u8 freesaveTailPad[4];
    // sizeof: 0x3???
};"""


def edit(path, old, new, what):
    """Apply one replacement and ASSERT it landed.

    Asserted per replacement, never in bulk. An edit script that checks only
    "the file changed" reports success when one of several replacements silently
    fails to match -- which shipped a screen with no draw block for two build
    cycles once already.
    """
    s = path.read_text()
    if new in s and old not in s:
        print(f"  = {what} (already applied)")
        return
    if old not in s:
        sys.exit(f"error: anchor for {what} not found in {path}")
    path.write_text(s.replace(old, new, 1))
    print(f"  + {what}")


def set_switches(path, value):
    """Drive all twelve FREE_* switches to `value`, and PROVE the end state.

    Idempotent on purpose -- an arm may already be in the wanted state -- so the
    check is not "did each line change" but "is every line now `value`". Those
    are different assertions and only the second one is true of a re-run.
    """
    other = "FALSE" if value == "TRUE" else "TRUE"
    s = path.read_text()
    names = re.findall(r"#define (FREE_\w+)\s+(?:TRUE|FALSE)", s)
    if len(names) != 12:
        sys.exit(f"error: expected 12 FREE_* switches in {path}, found {len(names)}")
    s = re.sub(rf"(#define FREE_\w+\s+){other}\b", rf"\g<1>{value}", s)
    still = re.findall(rf"#define (FREE_\w+)\s+{other}\b", s)
    if still:
        sys.exit(f"error: these switches did not reach {value}: {still}")
    if len(re.findall(rf"#define FREE_\w+\s+{value}\b", s)) != 12:
        sys.exit(f"error: expected 12 switches at {value} after the edit")
    path.write_text(s)
    print(f"  + all 12 FREE_* switches -> {value}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("fork", type=pathlib.Path, help="path to the freesave fork")
    ap.add_argument("--arm", required=True, choices=("off", "on", "swapped"),
                    help="which of the three builds to configure the tree for")
    args = ap.parse_args()

    fork = args.fork.resolve()
    for needed in ("src/main.c", "include/global.h", "include/config/save.h"):
        if not (fork / needed).exists():
            sys.exit(f"error: {fork} does not look like a pokeemerald fork "
                     f"(missing {needed})")

    print(f"freesave fixture -> {fork}  [arm: {args.arm}]")

    # Shared in every arm.
    (fork / "src/freesave_probe.c").write_text(PROBE_C)
    (fork / "include/freesave_probe.h").write_text(PROBE_H)
    print("  + src/freesave_probe.c, include/freesave_probe.h")
    main_c = fork / "src/main.c"
    edit(main_c, MAIN_INCLUDE_ANCHOR, MAIN_INCLUDE_ADD, "main.c include")
    edit(main_c, MAIN_HOOK_ANCHOR, MAIN_HOOK_ADD, "main.c hook call")

    # Arm-specific. Each arm resets the other arm's edits so the arms are
    # mutually exclusive rather than cumulative.
    global_h = fork / "include/global.h"
    save_h = fork / "include/config/save.h"

    set_switches(save_h, "TRUE" if args.arm == "on" else "FALSE")

    if args.arm == "swapped":
        edit(global_h, FILLER_OLD, FILLER_NEW, "global.h filler1 0x34 -> 0x30")
        edit(global_h, TAIL_OLD, TAIL_NEW, "global.h 4-byte tail pad")
    else:
        edit(global_h, FILLER_NEW, FILLER_OLD, "global.h filler1 restored")
        edit(global_h, TAIL_NEW, TAIL_OLD, "global.h tail pad removed")

    print("\nNext: build, then stash the triple under roms/%s/pokeemerald.{gba,sym,elf}\n"
          "      -- the SAME basename for every arm, or mGBA hands the next build a\n"
          "      brand-new empty .sav that reads exactly like a rejected one."
          % args.arm)


if __name__ == "__main__":
    main()
